/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const MappingInfo = IDL.Record({
  'timestamp' : Time,
  'swapId' : IDL.Text,
  'walletId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMappingInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMappingInfoByTimeRange' : IDL.Func([Time, Time], [], []),
  'getAllMappingInfo' : IDL.Func([], [IDL.Vec(MappingInfo)], ['query']),
  'getFirstMappingInfo' : IDL.Func([], [IDL.Opt(MappingInfo)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const MappingInfo = IDL.Record({
    'timestamp' : Time,
    'swapId' : IDL.Text,
    'walletId' : IDL.Text,
  });
  
  return IDL.Service({
    'addMappingInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMappingInfoByTimeRange' : IDL.Func([Time, Time], [], []),
    'getAllMappingInfo' : IDL.Func([], [IDL.Vec(MappingInfo)], ['query']),
    'getFirstMappingInfo' : IDL.Func([], [IDL.Opt(MappingInfo)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };